export const KCAL_PER_KG = 7500;
export const TOTAL_TARGET_KCAL = 60000;
export const TOTAL_TARGET_KG = 8;
export const DEFAULT_WEEKLY = 6000;
export const STORAGE_KEY = 'deficit_dashboard_v1';

export const ACCENT = '#f97316';
export const GREEN = '#22c55e';
export const RED = '#ef4444';

const QUOTES = [
    { text: "Discipline equals freedom.", author: "Jocko Willink" },
    { text: "The only way out is through.", author: "David Goggins" },
    { text: "Stay hard.", author: "David Goggins" },
    { text: "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", author: "David Goggins" },
    { text: "Self-discipline is the ultimate form of self-love.", author: "Alex Hormozi" },
    { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
    { text: "Talent you have naturally. Skill is only developed by hours and hours of work.", author: "Usain Bolt" },
    { text: "I've failed over and over and over again. And that is why I succeed.", author: "Michael Jordan" },
    { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
    { text: "Self-belief and hard work will always earn you success.", author: "Virat Kohli" },
    { text: "Nothing comes easy. Work hard for it.", author: "Virat Kohli" },
    { text: "You can't put a limit on anything. The more you dream, the further you get.", author: "Michael Phelps" },
    { text: "If you want to be the best, you have to do things that other people aren't willing to do.", author: "Michael Phelps" },
    { text: "The less you talk, the more you're listened to.", author: "Tom Brady" },
    { text: "You have a right to perform your duty, but not to the fruits of action.", author: "Krishna, Bhagavad Gita" },
    { text: "Perform your obligatory duty, because action is indeed better than inaction.", author: "Krishna, Bhagavad Gita" },
    { text: "The mind is restless, but it can be controlled by practice and detachment.", author: "Krishna, Bhagavad Gita" },
    { text: "A man is made by his beliefs. As he believes, so he is.", author: "Krishna, Bhagavad Gita" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
    { text: "Volume negates luck.", author: "Alex Hormozi" },
    { text: "Boring consistency beats exciting inconsistency.", author: "Alex Hormozi" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
    { text: "You must build callouses on your mind just like you build them on your hands.", author: "David Goggins" },
    { text: "The most important conversation you’ll ever have is the one you have with yourself.", author: "David Goggins" },
    { text: "When you think that you are done, you're only 40% into what your body's capable of doing.", author: "David Goggins" },
    { text: "Go get after it.", author: "Jocko Willink" },
    { text: "Extreme ownership. Leaders must own everything in their world. There is no one else to blame.", author: "Jocko Willink" },
    { text: "Don't count on motivation. Count on discipline.", author: "Jocko Willink" },
    { text: "If you want to be tougher, be tougher.", author: "Jocko Willink" },
    { text: "You don't need more time. You need more focus.", author: "Alex Hormozi" },
    { text: "The person who can sit in a room for 10 years and do the boring thing wins.", author: "Alex Hormozi" },
    { text: "You don't become confident by shouting affirmations. You become confident by a stack of undeniable proof.", author: "Alex Hormozi" },
    { text: "Work like there is someone working 24 hours a day to take it away from you.", author: "Mark Cuban" },
    { text: "I don't play for 90 minutes. I play until I win.", author: "Cristiano Ronaldo" },
    { text: "Your love makes me strong. Your hate makes me unstoppable.", author: "Cristiano Ronaldo" },
    { text: "Dedication, hard work all the time, and belief.", author: "Cristiano Ronaldo" },
    { text: "I'm not a perfectionist, but I like to feel that things are done well.", author: "Cristiano Ronaldo" },
    { text: "Maybe they hate me because I'm too good.", author: "Cristiano Ronaldo" },
    { text: "Everything negative—pressure, challenges—is all an opportunity for me to rise.", author: "Kobe Bryant" },
    { text: "Rest at the end, not in the middle.", author: "Kobe Bryant" },
    { text: "Mamba mentality is all about focusing on the process and trusting in the hard work.", author: "Kobe Bryant" },
    { text: "If you're afraid to fail, then you're probably going to fail.", author: "Kobe Bryant" },
    { text: "Obsession is natural.", author: "Kobe Bryant" },
    { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
    { text: "To be successful you have to be selfish, or else you never achieve.", author: "Michael Jordan" },
    { text: "Limits, like fears, are often just an illusion.", author: "Michael Jordan" },
    { text: "Step by step. I can't see any other way of accomplishing anything.", author: "Michael Jordan" },
    { text: "I want to be the best of all time.", author: "Virat Kohli" },
    { text: "On the field, you are a warrior. You have to give your 100%.", author: "Virat Kohli" },
    { text: "Whatever you want to do, do with full passion and work really hard towards it.", author: "Virat Kohli" },
    { text: "There are no shortcuts to success.", author: "Virat Kohli" },
    { text: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali" },
    { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
    { text: "It's lack of faith that makes people afraid of meeting challenges, and I believed in myself.", author: "Muhammad Ali" },
    { text: "If my mind can conceive it, and my heart can believe it—then I can achieve it.", author: "Muhammad Ali" },
    { text: "There is no such thing as 'natural' talent. There is only hard work.", author: "Michael Phelps" },
    { text: "I want to look back and say I did everything I could.", author: "Michael Phelps" },
    { text: "I won't predict anything historic. But I will predict that I'm going to do my best.", author: "Michael Phelps" },
    { text: "Consistency is what makes the average into the elite.", author: "Tom Brady" },
    { text: "I didn't come this far to only come this far.", author: "Tom Brady" },
    { text: "If you don't believe in yourself, why is anyone else going to believe in you?", author: "Tom Brady" },
    { text: "Too many people say 'no' to themselves before they even try.", author: "Joe Rogan" },
    { text: "Be the hero of your own movie.", author: "Joe Rogan" },
    { text: "Excellence is being able to perform at a high level over and over again.", author: "Joe Rogan" },
    { text: "One of the most fascinating things about humans is the capacity to self-correct.", author: "Joe Rogan" },
    { text: "Someone is sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett" },
    { text: "The man who says he can and the man who says he can't are both usually right.", author: "Henry Ford" },
    { text: "Better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.", author: "Krishna, Bhagavad Gita" },
    { text: "The soul is neither born, and nor does it die.", author: "Krishna, Bhagavad Gita" },
    { text: "Focus on your work, not the results.", author: "Krishna, Bhagavad Gita" },
    { text: "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.", author: "Krishna, Bhagavad Gita" },
    { text: "To the mind that is still, the whole universe surrenders.", author: "Lao Tzu" },
    { text: "You are what you do, not what you say you'll do.", author: "Carl Jung" },
    { text: "Other people's opinion of you does not have to become your reality.", author: "Les Brown" },
    { text: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Les Brown" },
    { text: "It’s not over until I win.", author: "Les Brown" },
    { text: "You must be willing to do the things today others won't do, in order to have the things tomorrow others won't have.", author: "Les Brown" },
    { text: "If you do what is easy, your life will be hard. If you do what is hard, your life will be easy.", author: "Les Brown" },
    { text: "The greatness of a man is not in how much wealth he acquires, but in his integrity.", author: "Bob Marley" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "The more you sweat in peace, the less you bleed in war.", author: "Navy SEAL Motto" },
    { text: "Comfort is the enemy of progress.", author: "P.T. Barnum" },
    { text: "Uncommon amongst uncommon.", author: "David Goggins" },
    { text: "Don't let your ego get in the way of your progress.", author: "Jocko Willink" },
    { text: "The only person you should try to be better than is the person you were yesterday.", author: "Matty Mullins" },
    { text: "I don't stop when I'm tired. I stop when I'm done.", author: "David Goggins" },
    { text: "Winning is not a sometime thing; it's an all the time thing.", author: "Vince Lombardi" },
    { text: "Practice like you've never won. Play like you've never lost.", author: "Michael Jordan" },
    { text: "Amateurs hope. Professionals work.", author: "Unknown" },
    { text: "Show up. Every single day.", author: "Joe Rogan" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
    { text: "Work in silence. Let your success be your noise.", author: "Frank Ocean" },
    { text: "Small daily improvements are the key to staggering long-term results.", author: "Unknown" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Hard work is a prison sentence only if it does not have a meaning.", author: "Malcolm Gladwell" },
    { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
    { text: "Great things come from hard work and perseverance. No excuses.", author: "Kobe Bryant" }
];
